.TH "TABLE" "1" "01-11-2020"
.SH NAME
table - a program to generate ascii tables from csv input.
.SH DESCRIPTION
.B table
is a program that I wrote to display the data in a prettier way.
.SH SYNOPSIS
table [OPTIONS...]
.PP
.BR table [OPTIONS...] [FILE]
.SH OPTIONS
.PP Program general informations
.TP
.B -h, --help
Prints a usage message to
.B
stderr
and exits.
.TP
.B -v, --ver
Displays the current version of this program
Uses the STYLE style to generate the table.
.TP
.B --no-header
Disable the header for the table
.SH BUGS
There are no known bugs.
.SH AUTHOR
Trachi Yassin
.SH SEE ALSO
.B vim
(1)
